name: SAAS-APP

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bun setup
        uses: oven-sh/setup-bun@v2

      - name: BUN test
        run: |
          bun install
          bun run dev
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          DATABASE_CONNECTION_TYPE: ${{ secrets.DATABASE_CONNECTION_TYPE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
          CLIENT_ID_GITHUB: ${{ secrets.CLIENT_ID_GITHUB }}
          CLIENT_SECRET_GITHUB: ${{ secrets.CLIENT_SECRET_GITHUB }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          HOST_URL: ${{ secrets.HOST_URL }}
          TURSO_API_KEY: ${{ secrets.TURSO_API_KEY }}
          TURSO_ORG_SLUG: ${{ secrets.TURSO_ORG_SLUG }}

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
